---
sidebar: sidebar 
permalink: docs/concept_hci_clusters.html 
summary: クラスタは、複数のストレージノードで構成されます。NetApp HCI ストレージクラスタには、少なくとも 2 つのストレージノードが必要です。クラスタはネットワーク上では 1 つの論理グループとして認識され、ブロックストレージとしてアクセスできます。 
keywords: netapp, hci, storage nodes, clusters, two-node cluster, three-node cluster, 2-node cluster, 3-node cluster 
---
= クラスタ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
クラスタとは、ストレージリソースまたはコンピューティングリソースを提供する複数のノードの集まりです。NetApp HCI 1.8 以降では、 2 ノードのストレージクラスタを構成できます。ストレージクラスタは、ネットワーク上では 1 つの論理グループとして認識され、ブロックストレージとしてアクセスできます。

NetApp HCI のストレージレイヤは NetApp Element ソフトウェアで提供され、管理レイヤは NetApp Element Plug-in for vCenter Server で提供されます。ストレージノードは、 Bond10G ネットワークインターフェイスを通じて相互に通信する一連のドライブを搭載したサーバです。各ストレージノードはストレージと管理の 2 つのネットワークに接続され、それぞれに 2 つの独立したリンクを使用して冗長性とパフォーマンスを確保します。各ノードには各ネットワークの IP アドレスが必要です。新しいストレージノードで構成されるクラスタを作成したり、既存のクラスタにストレージノードを追加してストレージの容量とパフォーマンスを拡張したりできます。



== 信頼できるストレージクラスタです

信頼できるストレージクラスタとは、 NetApp Hybrid Cloud Control でユーザの認証に使用するストレージクラスタです。

管理ノードにストレージクラスタが 1 つしかない場合は、信頼できるクラスタになります。管理ノードに複数のストレージクラスタがある場合は、それらのクラスタのいずれかが権限のあるクラスタとして割り当てられ、そのクラスタのユーザのみが NetApp Hybrid Cloud Control にログインできます。権限のあるクラスタを確認するには、「 get/mnode/about 」 API を使用します。応答では、「 token_url 」フィールドの IP アドレスは、権限のあるストレージクラスタの管理仮想 IP アドレス（ MVIP ）です。信頼できるクラスタにないユーザとして NetApp Hybrid Cloud Control にログインしようとすると、ログインに失敗します。

NetApp Hybrid Cloud Control の多くの機能は複数のストレージクラスタを使用するように設計されていますが、認証と許可には制限があります。認証と許可に関する制限事項として、信頼できるクラスタのユーザが、他のストレージクラスタのユーザでなくても、 NetApp Hybrid Cloud Control に関連付けられている他のクラスタに対して操作を実行できることがあります。複数のストレージクラスタの管理を開始する前に、権限のあるクラスタで定義されているユーザが同じ権限を持つ他のすべてのストレージクラスタに定義されていることを確認してください。

NetApp Hybrid Cloud Control を使用してユーザを管理できます。

複数のストレージクラスタの管理を開始する前に、権限のあるクラスタで定義されているユーザが同じ権限を持つ他のすべてのストレージクラスタに定義されていることを確認してください。を参照してください link:task_mnode_manage_storage_cluster_assets.html["ストレージクラスタアセットを作成および管理する"] 管理ノードのストレージクラスタアセットの使用の詳細については、を参照してください。



== 有効利用されない容量

新しく追加したノードがクラスタの合計容量の 50% を超えると、容量のルールに準拠するためにこのノードの一部の容量が使用できなくなります（「未使用」）。これは、ストレージ容量が追加されるまで有効です。容量のルールにも違反するような大規模なノードを追加すると、それまでに孤立していたノードは孤立しなくなり、新たに追加したノードが孤立する状態になります。この問題を回避するには、容量を常にペアで追加する必要があります。ノードが孤立すると、該当するクラスタエラーがスローされます。



== 2 ノードストレージクラスタ

NetApp HCI 1.8 以降では、 2 つのストレージノードでストレージクラスタをセットアップできます。

* 特定のタイプのノードを使用して、 2 ノードストレージクラスタを形成できます。を参照してください https://library.netapp.com/ecm/ecm_download_file/ECMLP2865021["NetApp HCI 1.8 リリースノート"]。
+

NOTE: 2 ノードクラスタの場合、ストレージノードのモデルは 480GB と 960GB のドライブで構成されるノードに制限され、ノードのモデルタイプは同じである必要があります。

* 2 ノードストレージクラスタは、大容量とハイパフォーマンスの要件に左右されないワークロードを使用する小規模な環境に最適です。
* 2 つのストレージノードに加えて、 2 ノードのストレージクラスタには、 NetApp HCI 監視ノード * が 2 つ含まれています。
+

NOTE: の詳細を確認してください link:concept_hci_nodes.html["監視ノード："]

* 2 ノードストレージクラスタを 3 ノードストレージクラスタに拡張することができます。3 ノードクラスタでは、ストレージノードの障害から自動で修復できるため、耐障害性が向上します。
* 2 ノードストレージクラスタには、従来の 4 ノードストレージクラスタと同じセキュリティ機能が備わっています。
* 2 ノードストレージクラスタでは、 4 ノードストレージクラスタと同じネットワークが使用されます。ネットワークは、 NetApp HCI の導入時に NetApp Deployment Engine ウィザードを使用してセットアップします。




=== ストレージクラスタのクォーラム

Element ソフトウェアは、選択したノードからストレージクラスタを作成します。これにより、クラスタ構成のレプリケートされたデータベースが保持されます。クラスタの耐障害性を維持するために、クラスタアンサンブルに参加するには、少なくとも 3 つのノードが必要です。2 ノードクラスタの監視ノードを使用して、有効なアンサンブルクォーラムを形成できるだけの十分なストレージノードがあることを確認します。アンサンブルの作成については、監視ノードよりもストレージノードが推奨されます。2 ノードストレージクラスタに関連する 3 ノード以上のアンサンブルでは、 2 つのストレージノードと 1 つの監視ノードが使用されます。


TIP: 3 ノードのアンサンブルに 2 つのストレージノードと 1 つの監視ノードがある場合、 1 つのストレージノードがオフラインになると、クラスタはデグレード状態になります。2 つの監視ノードのうち、アンサンブルでアクティブにできる監視ノードは 1 つだけです。2 つ目の監視ノードは、バックアップロールを実行するため、アンサンブルに追加できません。オフラインのストレージノードがオンライン状態に戻るか、交換用ノードがクラスタに追加されるまで、クラスタはデグレード状態のままです。

監視ノードで障害が発生した場合は、残りの監視ノードがアンサンブルに参加して、 3 ノードのアンサンブルを形成します。障害が発生した監視ノードの代わりに新しい監視ノードを導入できます。



=== 2 ノードストレージクラスタでの自動修復と障害処理

従来のクラスタの一部であるノードでハードウェアコンポーネントに障害が発生した場合、クラスタ内の他の使用可能なノードに障害が発生したコンポーネント上のデータがリバランシングされます。2 ノードストレージクラスタでは自動修復機能を使用できません。少なくとも 3 つの物理ストレージノードがクラスタで自動的に修復可能である必要があるためです。2 ノードクラスタの 1 つのノードで障害が発生した場合、 2 ノードクラスタではデータのコピーをもう 1 つ作成する必要はありません。残りのアクティブストレージノードでは、ブロックデータに対する新しい書き込みがレプリケートされます。障害が発生したノードを交換してクラスタに追加すると、 2 つの物理ストレージノード間でデータがリバランシングされます。



== 3 つ以上のノードを含むストレージクラスタ

2 つのストレージノードから 3 つのストレージノードに拡張することで、ノードとドライブの障害時に自動修復が可能になり、クラスタの耐障害性が向上します。ただし、追加の容量は提供されません。を使用してを展開できます link:task_hcc_expand_storage.html["NetApp Hybrid Cloud Control の UI"]。2 ノードクラスタから 3 ノードクラスタに拡張する場合は、容量が孤立する可能性があります（を参照） <<Stranded capacity>>）。インストール前に未使用の容量に関する警告が表示されます。1 つの監視ノードを使用して、ストレージノードに障害が発生した場合にアンサンブルクォーラムを維持することもできます。スタンバイ側の監視ノードも同様です。3 ノードストレージクラスタを 4 ノードクラスタに拡張すると、容量とパフォーマンスが向上します。4 ノードクラスタでは、監視ノードがクラスタクォーラムを形成する必要がなくなります。コンピューティングノードは最大 64 個、ストレージノードは 40 個まで拡張できます。



== 詳細については、こちらをご覧ください

* https://www.netapp.com/us/media/tr-4823.pdf["NetApp HCI 2 ノードストレージクラスタ | TR-4823"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
* http://docs.netapp.com/sfe-122/index.jsp["SolidFire と Element ソフトウェアドキュメントセンター"^]

