---
sidebar: sidebar 
permalink: docs/concept_nde_node_compatibility.html 
summary: 導入に必要な NetApp HCI ノードの互換性に関する要件について説明します。 
keywords: netapp, hci, deployment, compatibility, nodes 
---
= インベントリの選択とノードの互換性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
導入するノードを選択する際、同じ環境で組み合わせ可能なノード構成にはいくつかの制限があります。



== ストレージノードの互換性

NetApp HCI では、 SED （自己暗号化ドライブ）および FIPS 140-2 ドライブ暗号化機能を備えたストレージノードとドライブがサポートされます。NetApp HCI を導入または拡張する際 NetApp HCI には異なる暗号化レベルのノードを混在させることができますが、サポートされるのはより基本的な形式の暗号化のみです。たとえば、 FIPS 暗号化対応のストレージノードと SED 暗号化のみをサポートするノードが混在している場合、 SED 暗号化はサポートされますが、 FIPS ドライブ暗号化はサポートされません。


NOTE: FIPS ドライブ暗号化に対応したストレージノードをストレージクラスタに追加しても、 FIPS ドライブ暗号化機能は自動的には有効になりません。FIPS 対応ノードを含む環境を導入または拡張したら、 FIPS ドライブ暗号化を手動で有効にする必要があります。を参照してください https://docs.netapp.com/us-en/element-software/index.html["Element ソフトウェアのドキュメント"^] 手順については、を参照し

同じ導入環境で互換性を確保するためには、すべてのストレージノードが同じマイナーバージョンの Element ソフトウェアを実行している必要があります。たとえば、 Element 11.3.1 を実行しているストレージノードと Element 11.5 を実行しているストレージノードを混在させることはできません。


NOTE: ノードのハードウェア構成によっては、 H410S ストレージノードが、 H300S 、 H500S 、または H700S ストレージノードとしてインベントリリストに表示される場合があります。

NetApp HCI では、 2 ノードストレージクラスタでサポートされるストレージノードのモデルには制限があります。詳細については、を参照してください link:concept_hci_clusters.html#two-node-storage-clusters["2 ノードストレージクラスタ"] または NetApp HCI バージョンの『リリースノート』を参照してください。


NOTE: 2 ノードのストレージクラスタ環境では、ストレージノードのタイプは 480GB と 960GB のドライブを搭載したノードに制限されます。



== コンピューティングノードの互換性

コンピューティングノードをインベントリとして選択できるためには、ノードが次の要件を満たしている必要があります。

* VMware vMotion が適切に機能するように、すべてのコンピューティングノードの CPU 世代が一致している必要があります。インベントリからコンピューティングノードを 1 つ選択すると、そのノードとは CPU 世代が異なるノードは選択できなくなります。
* コンピューティングノードと GPU 対応のコンピューティングノードを同じコンピューティングクラスタ内に混在させることはできません。GPU 対応のコンピューティングノードを選択すると、 CPU のみのコンピューティングノードは選択できなくなります。その逆も同様です。
* コンピューティングノードで実行されているソフトウェアのバージョンが、導入環境をホストしている NetApp Deployment Engine とメジャーおよびマイナーバージョンの両方で一致している必要があります。一致していない場合は、 RTFI プロセスを使用してコンピューティングノードを再イメージ化する必要があります。手順については、 RTFI に関するネットアップの技術情報アーティクルを参照してください。
* コンピューティングノードを「 * コンピューティングノード * 」リストで選択できるようにするには、ネットワークトポロジページで選択したケーブル構成がコンピューティングノードに含まれている必要があります。
* 同じモデルのコンピューティングノードのネットワークケーブル構成は、コンピューティングクラスタ内で同じである必要があります。




== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire および Element ソフトウェアのドキュメント"^]

