---
sidebar: sidebar 
permalink: docs/concept_cg_hci_accounts.html 
summary: クラウドサービスが有効になっている各 NetApp HCI システムは、 NetApp Cloud Central アカウントに関連付けられています。 
keywords: netapp, hci, on premise, administrator, user account, cloud services, cluster 
---
= ユーザアカウント
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
システムのストレージリソースにアクセスするには、ユーザーアカウントを設定する必要があります。



== ユーザアカウント管理

ユーザアカウントは、 NetApp Element ソフトウェアベースのネットワーク上のストレージリソースへのアクセスを制御するために使用します。ボリュームを作成するには、ユーザアカウントが少なくとも 1 つ必要です。

ボリュームには、作成時にアカウントが割り当てられます。仮想ボリュームを作成した場合、アカウントはストレージコンテナになります。

その他の考慮事項をいくつか示します。

* アカウントには、そのアカウントに割り当てられているボリュームへのアクセスに必要な CHAP 認証が含まれています。
* アカウントには最大 2 、 000 個のボリュームを割り当てることができますが、 1 つのボリュームが属することのできるアカウントは 1 つだけです。
* ユーザアカウントは、 NetApp Element Management 拡張ポイントで管理できます。


NetApp Hybrid Cloud Control を使用して、次のタイプのアカウントを作成および管理できます。

* ストレージクラスタの管理者ユーザアカウント
* 権限のあるユーザアカウント
* ボリュームアカウント。ボリュームを作成したストレージクラスタのみに固有です。




== ストレージクラスタ管理者アカウント

NetApp Element ソフトウェアを実行するストレージクラスタには、次の 2 種類の管理者アカウントがあります。

* * プライマリクラスタ管理者アカウント * ：この管理者アカウントは、クラスタ作成時に作成されます。このアカウントは、クラスタへの最高レベルのアクセス権を持つプライマリの管理アカウントです。このアカウントは、 Linux システムの root ユーザに相当します。この管理者アカウントのパスワードを変更できます。
* * クラスタ管理者アカウント * ：クラスタ管理者アカウントには、クラスタ内で特定のタスクを実行するための限定的な管理アクセスを付与できます。各クラスタ管理者アカウントに割り当てられたクレデンシャルを使用して、ストレージシステム内での API や Element UI の要求が認証されます。



NOTE: ノード UI からクラスタ内のアクティブノードにアクセスするには、ローカル（ LDAP 以外）のクラスタ管理者アカウントが必要です。まだクラスタに含まれていないノードにアクセスする場合、アカウントのクレデンシャルは必要ありません。

クラスタ管理者アカウントの管理では、クラスタ管理者アカウントの作成、削除、編集、クラスタ管理者パスワードの変更、およびユーザのシステムアクセスを管理するための LDAP の設定を行うことができます。



== 権限のあるユーザアカウント

権限のあるユーザアカウントは、ノードおよびクラスタの NetApp Hybrid Cloud Control インスタンスに関連付けられているどのストレージアセットに対しても認証できます。このアカウントを使用すると、すべてのクラスタのボリューム、アカウント、アクセスグループなどを管理できます。

権限のあるユーザアカウントは、 NetApp Hybrid Cloud Control の右上のメニューでユーザ管理オプションを使用して管理しています。

。 link:concept_hci_clusters.html#authoritative-storage-clusters["信頼できるストレージクラスタです"] は、 NetApp Hybrid Cloud Control がユーザの認証に使用するストレージクラスタです。

信頼できるストレージクラスタで作成されたすべてのユーザが、 NetApp Hybrid Cloud Control にログインできます。他のストレージクラスタで作成されたユーザは、 Hybrid Cloud Control にログインできません。

* 管理ノードにストレージクラスタが 1 つしかない場合は、信頼できるクラスタになります。
* 管理ノードに複数のストレージクラスタがある場合は、それらのクラスタのいずれかが権限のあるクラスタとして割り当てられ、そのクラスタのユーザのみが NetApp Hybrid Cloud Control にログインできます。


NetApp Hybrid Cloud Control の多くの機能は複数のストレージクラスタで使用できますが、認証と許可には制限事項があります。認証と許可に関する制限事項として、信頼できるクラスタのユーザは、他のストレージクラスタのユーザでなくても、 NetApp Hybrid Cloud Control に関連付けられている他のクラスタに対しても操作を実行できます。複数のストレージクラスタの管理を開始する前に、権限のあるクラスタで定義されているユーザが同じ権限を持つ他のすべてのストレージクラスタに定義されていることを確認してください。NetApp Hybrid Cloud Control からユーザを管理できます。



== ボリュームアカウント

ボリューム固有のアカウントは、アカウントを作成したストレージクラスタにのみ固有です。これらのアカウントには、ネットワーク全体で特定のボリュームに対する権限を設定できますが、設定したボリューム以外に影響はありません。

ボリュームアカウントは、 NetApp Hybrid Cloud Control Volumes の表で管理されます。



== 詳細については、こちらをご覧ください

* link:task_hcc_manage_accounts.html["ユーザアカウントを管理する"]
* link:concept_hci_clusters.html["クラスタについて学習する"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

