---
sidebar: sidebar 
permalink: docs/concept_hci_nodes.html 
summary: ノードは、クラスタにグループ化され、ブロックストレージまたはコンピューティングリソースとしてアクセスされるハードウェアです。 
keywords: netapp, hci, storage nodes, volumes, compute nodes, witness nodes, management node 
---
= ノード
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノードは、ブロックストレージとコンピューティング機能を提供するためにクラスタにグループ化されたハードウェアリソースまたは仮想リソースです。

NetApp HCI および Element ソフトウェアでは、クラスタのさまざまなノードロールが定義されています。ノードのロールには、 * 管理ノード * 、 * ストレージノード * 、 * コンピューティングノード * 、 * NetApp HCI 監視ノード * の 4 種類があります。



== 管理ノード

管理ノード（ mNode とも呼ばれます）は、ストレージクラスタと通信して管理操作を実行しますが、ストレージクラスタのメンバーではありません。管理ノードは、 API 呼び出しを使用してクラスタに関する情報を定期的に収集し、この情報を Active IQ に報告してリモート監視（有効な場合）に利用します。管理ノードでは、クラスタノードのソフトウェアアップグレードの調整も担当します。

管理ノードは、 Element ソフトウェアベースの 1 つ以上のストレージクラスタと同時に実行される仮想マシン（ VM ）です。アップグレードに加え、監視と計測などのシステムサービスの提供、クラスタのアセットと設定の管理、システムテストとユーティリティの実行、ネットアップサポートによるトラブルシューティングアクセスの有効化にも使用されます。Element 11.3 リリース以降、管理ノードはマイクロサービスホストとして機能するようになりました。そのため、メジャーリリースを待つことなく、希望するソフトウェアサービスを更新できます。これらのマイクロサービスまたは管理サービス（ Active IQ コレクタ、 vCenter Plug-in 用の QoSSIOC 、管理ノードサービスなど）は、サービスバンドルとして頻繁に更新されます。



== ストレージノード

NetApp HCI ストレージノードは、 NetApp HCI システムのストレージリソースを提供するハードウェアです。ノード内のドライブには、データの格納用と管理用にブロックスペースとメタデータスペースが確保されます。各ノードには、 NetApp Element ソフトウェアの工場出荷時のイメージが含まれています。NetApp HCI ストレージノードは、 NetApp Element Management 拡張ポイントを使用して管理できます。



== コンピューティングノード

NetApp HCI コンピューティングノードは、 NetApp HCI 環境での仮想化に必要な、 CPU 、メモリ、ネットワークなどのコンピューティングリソースを提供するハードウェアです。各サーバは VMware ESXi を実行するため、 vSphere のホストおよびクラスタメニューにあるプラグイン以外で NetApp HCI コンピューティングノードの管理（ホストの追加または削除）を行う必要があります。コンピューティングノードは、 4 ノードストレージクラスタと 2 ノードストレージクラスタのどちらであるかに関係なく、 NetApp HCI 環境では最低 2 つの数が維持されます。



== 監視ノード

NetApp HCI 監視ノードは、 Element ソフトウェアベースのストレージクラスタと並行してコンピューティングノードで実行される VM です。監視ノードでは、スライスサービスまたはブロックサービスがホストされません。監視ノードを使用すると、ストレージノードに障害が発生した場合のストレージクラスタの可用性を確保できます。監視ノードは、他のストレージノードと同じ方法で管理およびアップグレードできます。ストレージクラスタには、最大 4 つの監視ノードを含めることができます。主な目的は、有効なアンサンブルクォーラムを形成できるだけの十分な数のクラスタノードが存在することを確認することです。

|===


 a| 
* ベストプラクティス：監視ノードの VM でコンピューティングノードのローカルデータストアを使用するように設定する（ NDE のデフォルト設定）。 SolidFire ストレージボリュームなどの共有ストレージには設定しないでください。VM が自動的に移行されないようにするには、監視ノード VM の Distributed Resource Scheduler （ DRS ）自動化レベルを「 * Disabled 」に設定します。これにより、両方の監視ノードが同じコンピューティングノードで実行されないようにし、非ハイアベイラビリティ（ HA ）ペア構成を作成することができます。

|===

TIP: の詳細を確認してください link:hci_prereqs_witness_nodes.html["監視ノードのリソース要件"] および link:hci_prereqs_ip_address.html["監視ノードの IP アドレスの要件"]。


NOTE: 2 ノードストレージクラスタでは、監視ノードに障害が発生した場合の冗長性を確保するために、最低 2 つの監視ノードが導入されます。NetApp HCI のインストールプロセスで監視ノードがインストールされると、 VM テンプレートが VMware vCenter に格納されます。これを使用して、誤って削除された場合、失われた場合、または破損した場合に監視ノードを再導入できます。また、監視ノードをホストしていた障害コンピューティングノードと交換する必要がある場合は、テンプレートを使用して監視ノードを再導入することもできます。手順については、 2 ノードおよび 3 ノードのストレージクラスタに対する監視ノードの再導入 * を参照してください link:task_hci_h410crepl.html["こちらをご覧ください"]。



== 詳細については、こちらをご覧ください

* https://www.netapp.com/pdf.html?item=/media/9489-tr-4823.pdf["NetApp HCI 2 ノードストレージクラスタ | TR-4823"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
* http://docs.netapp.com/sfe-122/index.jsp["SolidFire と Element ソフトウェアドキュメントセンター"^]

