---
sidebar: sidebar 
permalink: docs/hci_prereqs_network_configuration.html 
summary: NetApp HCI のネットワーク構成オプションについて説明します。 
keywords: netapp, hci, cabling, network configuration 
---
= ネットワーク構成：
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp HCI では、複数の異なるネットワークケーブル配線と VLAN 構成を使用できます。導入を成功させるためには、ネットワーク構成を計画することが重要です。



== 必要なネットワークセグメント

NetApp HCI には、管理トラフィック、ストレージトラフィック、仮想化トラフィック（仮想マシンと VMware vMotion のトラフィックを含む）の少なくとも 3 つのネットワークセグメントが必要です。仮想マシンと vMotion のトラフィックを分けることもできます。これらのネットワークセグメントは、通常、 NetApp HCI ネットワークインフラ内で論理的に分離された VLAN として存在します。

これらのネットワークにコンピューティングノードとストレージノードを接続する方法は、ネットワークを設計する方法とノードをケーブル接続する方法によって異なります。このガイドで使用するネットワーク図は、次のネットワークに基づいています。

|===
| ネットワーク名 | VLAN ID 


| 管理 | 100 


| ストレージ | 105 


| vMotion | 107 


| 仮想マシン | 200 、 201 
|===
NetApp Deployment Engine で NetApp HCI ノードを自動的に検出して設定するには、ノード上の SFP+ / SFP28 インターフェイスに使用されているすべてのスイッチポートで、タグなし VLAN またはネイティブ VLAN として使用できるネットワークセグメントが必要です。これにより、すべてのノード間で検出と導入のためのレイヤ 2 通信が可能になります。ネイティブ VLAN がない場合、すべてのノードの SFP+ / SFP28 インターフェイスに VLAN および IPv4 アドレスを手動で設定し、検出されるようにする必要があります。このドキュメントのネットワーク構成例では、この目的で管理ネットワーク（ VLAN ID 100 ）を使用しています。

NetApp Deployment Engine を使用すると、初期導入時にコンピューティングノードとストレージノードのネットワークを簡単に設定できます。vCenter や管理ノードなどの一部の組み込みの管理コンポーネントを専用のネットワークセグメントに配置することができます。これらのネットワークセグメントには、 vCenter や管理ノードがストレージおよびコンピューティングの管理ネットワークと通信できるようにするためのルーティングが必要です。ほとんどの環境では、これらのコンポーネントは同じ管理ネットワーク（この例では VLAN ID 100 ）を使用します。


NOTE: 仮想マシンのネットワークは vCenter を使用して設定します。NetApp HCI 環境のデフォルトの仮想マシンネットワーク（ポートグループ「 VM_Network 」）では VLAN ID は設定されません。複数の仮想マシンネットワークをタグ付けして使用する予定の場合は（前述の例の VLAN ID 200 および 201 ）、ネットワーク計画に最初からそれらのネットワークを含めるようにしてください。



== ネットワーク構成とケーブル配線のオプション

H410C コンピューティングノードには、シンプルな配線の 2 ケーブルネットワーク構成を使用できます。この構成では、 2 つの SFP+ / SFP28 インターフェイスに加え、 IPMI 通信用にオプションで RJ45 インターフェイス（必須ではありませんが使用することを推奨）を使用します。これらのノードでは、 2 つの RJ45 インターフェイスと 4 つの SFP28 / SFP+ インターフェイスを備えた 6 ケーブル構成を使用することもできます。

H410S および H610S ストレージノードは、 4 つのネットワークポート（ポート A~D ）を使用するネットワークトポロジをサポートします。

コンピューティングノードは、ハードウェアプラットフォームに応じて、次の 3 種類のネットワークトポロジをサポートします。

|===
| 設定オプション | H410C ノードのケーブル接続 | H610C ノードのケーブル配線 | H615C ノードのケーブル接続 


| オプション A | ポート D と E を使用する 2 本のケーブル | ポート C と D を使用する 2 本のケーブル | ポート A と B を使用する 2 本のケーブル 


| オプション B | 6 本のケーブルでポート A ~ F を使用 | 使用できません | 使用できません 


| オプション C 3+| オプション B と同様ですが、管理、ストレージ、および vMotion ネットワーク用のスイッチにネイティブ VLAN （アクセスポート）が搭載されています 
|===
正しい数のケーブルが接続されていないノードを導入することはできません。たとえば、ケーブル 6 本の構成では、ポート D と E しか接続されていないコンピューティングノードを導入することはできません。


NOTE: NetApp HCI のネットワーク設定は、導入後にインフラのニーズに合わせて調整することができます。ただし、 NetApp HCI リソースを拡張する場合は、新しいノードのケーブル構成を既存のコンピューティングノードおよびストレージノードと同じにする必要があります。

[NOTE]
====
ネットワークでジャンボフレームがサポートされていないために NetApp Deployment Engine で障害が発生した場合は、次のいずれかの対処方法を実行します。

* 静的 IP アドレスを使用して、 Bond10G ネットワークで 9000 バイトの最大伝送ユニット（ MTU ）を手動で設定してください。
* Bond10G ネットワークで 9000 バイトのインターフェイス MTU をアドバタイズするように動的ホスト構成プロトコルを設定します。


====
.ネットワーク構成オプション
* link:hci_prereqs_network_configuration_option_A.html["ネットワーク構成オプション A"]
* link:hci_prereqs_network_configuration_option_B.html["ネットワーク構成オプション B"]
* link:hci_prereqs_network_configuration_option_C.html["ネットワーク構成オプション C"]


[discrete]
== 詳細については、こちらをご覧ください

* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI のリソースページ"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

