---
sidebar: sidebar 
permalink: docs/hci_prereqs_network_switch.html 
summary: このバージョンの NetApp HCI の新機能について説明します。 
keywords: netapp, hci, network, switch, requirements 
---
= ネットワークとスイッチの要件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: netapp, hci, network, switch, requirements


[role="lead"]
導入を成功させるためには、 NetApp HCI に使用するスイッチで特別な設定が必要になります。以降に記載するそれぞれの要件を環境に実装する手順については、使用するスイッチのドキュメントを参照してください。

NetApp HCI 環境には、次のトラフィックタイプごとに 1 つ、少なくとも 3 つのネットワークセグメントが必要です。

* 管理
* VMware vMotion
* ストレージ / データ


NetApp H シリーズのコンピューティングノードおよびストレージノードのモデルや計画しているケーブル構成に応じて、別々のスイッチを使用してこれらのネットワークを物理的に分離するか、または VLAN を使用して論理的に分離することができます。ただしほとんどの環境では、これらのネットワーク（およびその他の仮想マシンネットワーク）を VLAN を使用して論理的に分離する必要があります。

コンピューティングノードとストレージノードは、導入中およびその前後に通信可能である必要があります。ストレージノードとコンピューティングノードに別々の管理ネットワークを実装する場合は、それらの管理ネットワーク間にネットワークルートが確立されていることを確認してください。これらのネットワークにはゲートウェイが割り当てられている必要があり、ゲートウェイ間にルートが必要です。ノードと管理ネットワーク間の通信を確保するために、新しい各ノードにゲートウェイが割り当てられていることを確認してください。

NetApp HCI スイッチの要件は次のとおりです。

* NetApp HCI ノードに接続するスイッチポートは、すべてスパニングツリーのエッジポートとして設定する必要があります。
+
** Cisco スイッチでは、スイッチモデル、ソフトウェアバージョン、およびポートタイプに応じて、次のいずれかのコマンドを使用してこの操作を実行できます。
+
*** 「 panning - tree port type edge 」を選択します
*** 「パンニングツリーポートタイプエッジトランク」
*** ' パンツリー portfast
*** ' パンツリー portfast trunk


** Mellanox スイッチでは ' panning tree port type edge コマンドを使用してこれを実行できます


* NetApp HCI ノードには、アウトオブバンド管理を除くすべてのネットワーク機能用に冗長なポートがあります。最大限の耐障害性を実現するには、これらのポートを 2 つのスイッチに分け、従来の階層型アーキテクチャまたはレイヤ 2 のスパイン / リーフ型アーキテクチャへの冗長なアップリンクを確保します。
* ストレージ、仮想マシン、 vMotion の各トラフィックを処理するスイッチは、ポートあたり 10GbE 以上の速度をサポートする必要があります（ポートあたり最大 25GbE がサポートされます）。
* 管理トラフィックを処理するスイッチは、ポートあたり 1GbE 以上の速度をサポートする必要があります。
* ストレージおよび vMotion のトラフィックを処理するスイッチポートには、ジャンボフレームを設定する必要があります。インストールを成功させるには、ホストが 9000 バイトのパケットをエンドツーエンドで送信できる必要があります。
* 各ホストの管理 NIC ポートに設定されているサイズの MTU を使用できるように、管理ネットワークスイッチポートを設定する必要があります。たとえば、ホスト管理ネットワークポートの MTU サイズが 1750 バイトの場合は、少なくとも 1 、 750 バイトの MTU を使用できるように管理ネットワークスイッチポートを設定する必要があります（管理ネットワークの MTU は 9 、 000 バイトである必要はありません）。MTU 設定はエンドツーエンドで一貫した値にする必要があります
* すべてのストレージノードとコンピューティングノード間のラウンドトリップネットワークレイテンシを 2 ミリ秒以下にする必要があります。


すべての NetApp HCI ノードは、専用の管理ポートを通じてアウトオブバンド管理機能を提供します。NetApp H300 、 H300E 、 H500S 、 H500E 、 H700S 、 H700E 、および H410C のノードでは、ポート A を介した IPMI アクセスも可能ですベストプラクティスとして、環境内のすべてのノードでアウトオブバンド管理を設定し、 NetApp HCI のリモート管理を容易にすることを推奨します。

[discrete]
== 詳細については、こちらをご覧ください

* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI のリソースページ"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

