---
sidebar: sidebar 
permalink: docs/task_nde_select_inventory.html 
summary: 導入時に NetApp HCI ノードインベントリを選択する方法について説明します。 
keywords: netapp, hci, deployment, compatibility, nodes 
---
= インベントリを選択します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Deployment Engine は、「 * インベントリ」ページで利用可能なコンピューティングノードとストレージノードを自動的に検出し、すべての NetApp HCI リソースを選択して導入環境に追加できるようにします。導入の要件を満たしていないノードは選択できず、問題がエラーとして示されます。ノードの行のエラーにカーソルを合わせると、説明が表示されます。Inventory ページでノードインベントリを選択すると、 NetApp Deployment Engine をホストしているストレージノードが自動的に選択され、選択を解除することはできません。

.必要なもの
インベントリの検出が正しく機能するためには、ジャンボフレームを有効にする必要がありますインベントリにノードがまったく表示されない場合や、一部のノードしか表示されない場合は、 NetApp HCI ノードに使用されているスイッチポート（すべての SFP+ / SFP28 インターフェイス）にジャンボフレームが設定されていることを確認します。

.手順
. [* Inventory] ページで、使用可能なノードのリストを確認します。
+
システムがインベントリを検出できない場合は、エラーが表示されます。エラーを修正してから続行してください。IP アドレスの割り当てに DHCP を使用するシステムの場合は、ストレージリソースとコンピューティングリソースがすぐにインベントリに表示されないことがあります。

. オプション：リソースがすぐにインベントリに表示されない場合、またはエラーに対処してインベントリを更新する必要がある場合は、 [* インベントリの更新 * ] をクリックします。インベントリを複数回更新しなければならない場合があります。
. オプション：ノードタイプなどのノード属性でインベントリをフィルタリングするには、次の手順を実行します。
+
.. [ 計算ノード * ] または [ ストレージノード * ] リストのヘッダーで [ * フィルタ * ] をクリックします。
.. ドロップダウンリストから条件を選択します。
.. ドロップダウンリストの下に、条件を満たす情報を入力します。
.. [ フィルタを追加（ Add Filter ） ] をクリックします
.. アクティブなフィルタの横にある *X* をクリックして個々のフィルタをクリアするか、フィルタのリストの上にある *X* をクリックしてすべてのフィルタをクリアします。


. システムに付属しているすべてのコンピューティングノードを * コンピューティングノード * リストから選択します。
+
導入を進めるには、少なくとも 2 つのコンピューティングノードを選択する必要があります。

. システムに付属しているすべてのストレージノードを * ストレージノード * リストから選択します。
+
導入を進めるには、少なくとも 2 つのストレージノードを選択する必要があります。

. オプション：ストレージノードの選択ボックスにフラグが設定されている場合、そのストレージノードはストレージクラスタの総容量の 33% を超えています。次の手順を実行します。
+
** フラグが設定されたストレージノードの選択ボックスをオフにします。
** ストレージクラスタの容量がノード間でより均等に分散されるように、追加のストレージノードを選択します。


. [* Continue （続行） ] をクリックします




== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
* https://www.netapp.com/us/documentation/hci.aspx["NetApp HCI のリソースページ"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire および Element ソフトウェアのドキュメント"^]

