---
sidebar: sidebar 
permalink: docs/task_hcc_manage_vol_access_groups.html 
summary: NetApp HCI ストレージボリュームを操作するための新しいボリュームアクセスグループの追加、システムからのボリュームアクセスグループの削除、既存のボリュームアクセスグループの編集、ボリュームアクセスグループの詳細の表示を行う方法について説明します。 
keywords: netapp, hci, on premise, cluster, element 
---
= ボリュームアクセスグループを作成および管理します
:allow-uri-read: 


[role="lead"]
NetApp Hybrid Cloud Control を使用して、新しいボリュームアクセスグループを作成したり、名前、関連付けられているイニシエータ、またはアクセスグループの関連付けられているボリュームを変更したり、既存のボリュームアクセスグループを削除したりできます。

.必要なもの
* この NetApp HCI システムの管理者クレデンシャルが必要です。
* 管理サービスをバージョン 2.15.28 以上にアップグレードしておきます。NetApp Hybrid Cloud Control のストレージ管理は、それよりも前のバージョンのサービスバンドルでは利用できません。
* ボリュームアクセスグループの論理的な命名規則があることを確認します。




== ボリュームアクセスグループを追加

NetApp Hybrid Cloud Control を使用して、ストレージクラスタにボリュームアクセスグループを追加できます。

.手順
. NetApp HCI または Element ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
. ダッシュボードの左側のナビゲーションメニューで、ストレージクラスタの名前を展開します。
. [* Volumes （ボリューム） ] を選択します
. [* アクセスグループ *] タブを選択します。
. [ アクセスグループの作成 *] ボタンを選択します。
. 表示されたダイアログで、新しいボリュームアクセスグループの名前を入力します。
. （オプション）「 * Initiators * 」セクションで、新しいボリュームアクセスグループに関連付けるイニシエータを 1 つ以上選択します。
+
イニシエータをボリュームアクセスグループに関連付けると、そのイニシエータはグループ内の各ボリュームに認証なしでアクセスできます。

. （オプション） * Volumes * セクションで、このボリュームアクセスグループに含めるボリュームを 1 つ以上選択します。
. [ アクセスグループの作成 *] を選択します。




== ボリュームアクセスグループを編集します

NetApp Hybrid Cloud Control を使用して、既存のボリュームアクセスグループのプロパティを編集できます。アクセスグループの名前、関連付けられているイニシエータ、または関連付けられているボリュームを変更できます。

.手順
. NetApp HCI または Element ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
. ダッシュボードの左側のナビゲーションメニューで、ストレージクラスタの名前を展開します。
. [* Volumes （ボリューム） ] を選択します
. [* アクセスグループ *] タブを選択します。
. アクセスグループテーブルの *Actions * 列で、編集する必要があるアクセスグループのオプションメニューを展開します。
. オプションメニューで、 * 編集 * を選択します。
. 名前、関連付けられているイニシエータ、または関連付けられているボリュームに必要な変更を加えます。
. [ 保存（ Save ） ] を選択して変更を確認します。
. *Access Groups* テーブルで、アクセスグループに変更が反映されていることを確認します。




== ボリュームアクセスグループを削除する

NetApp Hybrid Cloud Control を使用してボリュームアクセスグループを削除し、同時にこのアクセスグループに関連付けられているイニシエータをシステムから削除することができます。

.手順
. NetApp HCI または Element ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
. ダッシュボードの左側のナビゲーションメニューで、ストレージクラスタの名前を展開します。
. [* Volumes （ボリューム） ] を選択します
. [* アクセスグループ *] タブを選択します。
. アクセスグループテーブルの *Actions * 列で、削除するアクセスグループのオプションメニューを展開します。
. オプションメニューで、 * 削除 * を選択します。
. アクセスグループに関連付けられているイニシエータを削除しない場合は、「 * このアクセスグループ内のイニシエータを削除する * 」チェックボックスの選択を解除します。
. [ はい ] を選択して、削除操作を確認します。




== 詳細については、こちらをご覧ください

* link:concept_hci_volume_access_groups.html["ボリュームアクセスグループについて学習する"]
* link:task_hcc_manage_initiators.html#add-initiators-to-a-volume-access-group["ボリュームアクセスグループにイニシエータを追加します"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

