---
sidebar: sidebar 
permalink: docs/task_nde_review_deploy.html 
summary: 最終的な構成を確認し、これらの設定を使用して NetApp HCI を導入する方法について説明します。 
keywords: netapp, hci, deployment, review, deploy 
---
= 構成を確認し、導入します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
導入を開始する前に、指定した情報を確認できます。続行する前に、誤った情報や不完全な情報を修正することもできます。


NOTE: 導入時、管理ノードのインストールプロセスでは、 Element ストレージクラスタに「 NetApp-HCI - 」で始まる名前のボリュームが作成されます。また、「 tenant_ 」で始まる名前の SolidFire アカウントも作成されます。これらのボリュームやアカウントは削除しないでください。削除すると、管理機能が失われます。

.手順
. オプション：インストール情報を CSV 形式でダウンロードするには、「 * Download * 」アイコンを選択します。このファイルを保存し、あとで設定情報として参照できます。
+

NOTE: CSV ファイルをインストールプロファイルとして NetApp Deployment Engine （ NDE ）の「 * Installation Profile * 」ページにインポートできます。これは、将来のインストールで必要になった場合にのみ可能です。

. 各セクションを展開し、情報を確認します。すべてのセクションを一度に展開するには、 * すべて展開 * を選択します。
. オプション：表示されているセクションの情報を変更するには、次の手順を実行します。
+
.. 対応するセクションで * Edit * を選択します。
.. 必要な変更を行います。
.. [* Review * （レビュー） ] ページが表示されるまで、 [* Continue （続行） ] を選択します。以前の設定は各ページに保存されます。
.. 手順 2 と 3 を繰り返して、必要なその他の変更を行います。


. ネットアップがホストしている SolidFire Active IQ サーバにクラスタの統計情報とサポート情報を送信しないようにする場合は、最後のチェックボックスをオフにします。
+
これにより、 NetApp HCI のリアルタイムの健常性診断の監視機能が無効になります。この機能を無効にすると、ネットアップによる NetApp HCI のプロアクティブなサポートと監視が行われなくなるため、本番環境が影響を受ける前に問題を検出して解決できなくなります。

. すべての情報が正しい場合は、「 * 導入の開始 * 」を選択します。
+
ダイアログボックスが表示されます。最終セットアッププロセスでネットワーク接続に問題が発生したり、電源が切断されたりした場合、またはブラウザセッションが切断された場合は、ダイアログに表示された URL をコピーして、最後のセットアップの進捗ページを参照できます。

. ダイアログ内の情報を確認し、 ［ * クリップボードにコピー * ］ を選択して URL をクリップボードにコピーします。
. URL をコンピュータ上のテキストファイルに保存します。
. 展開を続行する準備ができたら、 * OK * を選択します。
+
導入が開始され、進捗状況ページが表示されます。導入が完了するまでは、ブラウザウィンドウを閉じたり進捗状況ページから移動したりしないでください。何らかの理由でブラウザセッションが切断された場合は、前の手順でコピーした URL を参照して（および表示されるセキュリティ警告を受け入れて）、最後のセットアップの進捗状況ページへのアクセスを再確立できます。

+

NOTE: 導入に失敗した場合は、エラーメッセージのテキストを保存してネットアップサポートにお問い合わせください。

+
導入が完了すると、コンピューティングノードが複数回リブートしてからサービスを開始できるようになることがあります。



.完了後
「 vSphere の起動」を選択して、 NetApp HCI の使用を開始します。

[NOTE]
====
* vSphere 6.7 を使用する NetApp HCI 環境では、このリンクをクリックすると、 HTML5 vSphere Web インターフェイスが起動します。vSphere 6.5 を使用する環境では、このリンクをクリックすると Adobe Flash vSphere Web インターフェイスが起動します。
* ストレージノードを 2 つ構成または 3 つ構成する場合、コンピューティングノード上のローカルデータストアを使用するように監視ノードが設定されます。その結果、 vSphere Client に「 Datastore usage on disk * 」という警告が 2 つ表示されます。続行するには、警告ごとに [ 緑にリセット ] リンクを選択します。


====


== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
* https://www.netapp.com/us/documentation/hci.aspx["NetApp HCI のリソースページ"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire および Element ソフトウェアのドキュメント"^]

