---
sidebar: sidebar 
permalink: docs/task_nde_access_dhcp.html 
summary: DHCP を使用して IP アドレスを割り当てる環境で NetApp Deployment Engine にアクセスする方法について説明します。 
keywords: netapp, hci, netapp deployment engine, deployment, engine, deploy, access, dhcp 
---
= DHCP を使用している環境で NetApp Deployment Engine にアクセスします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
IPv4 の設定を DHCP から自動的に取得するようにサーバを構成している環境では、いずれかのストレージノードの Bond1G インターフェイスに割り当てられた IPv4 アドレスを使用して NetApp Deployment Engine にアクセスできます。このストレージノードの IPv4 アドレスは USB メモリを使用して取得できます。NetApp Deployment Engine は、 DHCP から割り当てられた IPv4 アドレスを使用している他のコンピューティングノードとストレージノードを自動的に検出します。ネットワークに特別な要件がないかぎり、この方法は使用しないでください。

.必要なもの
* 自分またはネットワーク管理者が、『セットアップガイド』ドキュメントのタスクを完了している。
* NetApp HCI ノードに物理的にアクセスできるようにしておきます。
* すべての NetApp HCI ノードの電源をオンにしておきます。
* NetApp HCI の管理ネットワークとストレージネットワークで DHCP を有効にしておきます。
* DHCP アドレスプールは、 NetApp HCI ノードごとに 2 つの IPv4 アドレスを格納するのに十分な大きさです。



NOTE: NetApp HCI を適切に導入するためには、環境内のすべてのノードの IPv4 アドレスを DHCP から取得したアドレスか自動で設定したアドレスのどちらかにする必要があります（ IPv4 アドレスの割り当て方法を混在させることはできません）。

.このタスクについて
DHCP をストレージネットワーク（ Bond10G インターフェイス）にのみ使用している場合は、リンクに記載されている手順を使用してください。 link:task_nde_access_no_dhcp.html["DHCP を使用していない環境では、 NetApp Deployment Engine にアクセスします"] NetApp Deployment Engine にアクセスします。

.手順
. ノードが IP アドレスを要求するまで数分待ちます。
. ストレージノードを選択し、そのノードに USB メモリを挿入します。そのまま少なくとも 5 秒間待ちます。
. USB スティックを取り外し、コンピュータに挿入します。
. 'Re'DME.html' ファイルを開きますNetApp Deployment Engine のユーザインターフェイスが表示されます。


[discrete]
== 詳細については、こちらをご覧ください

* link:firmware_driver_versions.html["NetApp HCI でサポートされるファームウェアとESXiドライバのバージョン、NetApp HCI ストレージノードでサポートされるファームウェアのバージョンとファームウェアのバージョン"]

