---
sidebar: sidebar 
permalink: docs/task_nde_configure_credentials.html 
summary: NetApp HCI の導入時に VMware vSphere を設定する方法について説明します。 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= NetApp HCI クレデンシャルを設定する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: netapp, hci, netapp deployment engine, deployment, vsphere, vcenter, credentials, user accounts, administrator


[role="lead"]
導入時に、新しく導入する VMware vSphere 環境、 NetApp HCI のコンピューティングリソースとストレージリソース、および管理ノードで使用する一連のクレデンシャルを定義します。既存の vSphere 環境に NetApp HCI を導入する場合、既存の vCenter Server にこれらのクレデンシャルは適用されません。

.このタスクについて
NetApp HCI Deployment Engine で設定するクレデンシャルについては、次の点に注意してください。

* * NetApp Hybrid Cloud Control （ HCC ）または Element UI * ：導入の成功時に NetApp HCC または Element ユーザインターフェイスにログインするには、この導入手順で指定したユーザ名とパスワードを使用します。
* *VMware vCenter*: vCenter にログインするには ( 展開の一部としてインストールされている場合 ) 、ユーザ名にサフィックス @vsphere. local またはビルトイン Administrator@vsphere.loca l のユーザアカウント、およびこの展開手順で指定されているパスワードを使用します。
* *VMware ESXi* ：コンピューティング・ノードで ESXi にログインするには ' ユーザー名 root と ' この導入手順で指定されているパスワードを使用します


VMware vCenter インスタンスと連携するために、 NetApp Hybrid Cloud Control では次のいずれかを使用します。

* 導入の一環としてインストールされた vCenter インスタンス上の組み込みの「 Administrator@vsphere.loca 」ユーザアカウント。
* 既存の VMware vCenter Server への NetApp HCI 環境の接続に使用した vCenter クレデンシャル。


.手順
. [*Credentials] ページで、 [*User Name*] フィールドにユーザ名を入力します。
. [* パスワード * ] フィールドにパスワードを入力します。パスワードは、「 * Password must contain * 」ボックスに表示されるパスワード基準に準拠している必要があります。
. パスワードの再入力 * フィールドにパスワードを確認します。
. [* Continue （続行） ] をクリックします


[discrete]
== 詳細については、こちらをご覧ください

* link:firmware_driver_versions.html["NetApp HCI でサポートされるファームウェアとESXiドライバのバージョン、NetApp HCI ストレージノードでサポートされるファームウェアのバージョンとファームウェアのバージョン"]
* vCenter と ESXi のクレデンシャルをあとで更新する場合は、を参照してください link:task_hci_credentials_vcenter_esxi.html["vCenter または ESXi のクレデンシャルを更新します"]。

