---
sidebar: sidebar 
permalink: docs/task_mnode_run_system_utilities.html 
summary: クラスタサポートバンドルを作成または削除したり、ノード設定をリセットしたり、ネットワークを再起動したりできます。 
keywords: netapp, element, management node ui, mnode ui, system utilities 
---
= 管理ノードからシステムユーティリティを実行します
:allow-uri-read: 


[role="lead"]
管理ノードのノード UI を使用して、クラスタサポートバンドルの作成または削除、ノード設定のリセット、ネットワークの再起動を実行できます。

.手順
. 管理ノードの管理クレデンシャルを使用して、ノード管理ノード UI を開きます。
. [ システムユーティリティ ] をクリックします。
. 実行するユーティリティのボタンをクリックします。
+
.. * Control Power * ：ノードをリブート、電源再投入、またはシャットダウンします。次のいずれかのオプションを指定します。
+

IMPORTANT: この処理を実行すると、ネットワーク接続が一時的に失われます。

+
*** * アクション *: オプションには「再起動」と「停止」 ( 電源オフ ) が含まれます。
*** * Wakeup Delay * ：ノードがオンラインに戻るまでの時間。


.. * クラスタサポートバンドルの作成 * ：クラスタ内のノードについてネットアップサポートの診断を受けるためのクラスタサポートバンドルを作成します。次のオプションを指定します。
+
*** * Bundle Name * ：作成された各サポートバンドルの一意の名前。名前を指定しない場合、「 supportbundle 」とノード名がファイル名として使用されます。
*** * Mvip * ：クラスタの MVIP 。バンドルは、クラスタ内のすべてのノードから収集されます。このパラメータは、 Nodes パラメータを指定しない場合のみ必要です。
*** * Nodes * ：バンドルを収集するノードの IP アドレス。バンドルの収集元のノードを指定するには、 Nodes または Mvip のいずれかを使用します。両方を使用することはできません。このパラメータは、 Mvip を指定しない場合は必須です。
*** * Username * ：クラスタ管理者ユーザ名。
*** * Password * ：クラスタ管理者のパスワード。
*** * Allow Incomplete * ： 1 つ以上のノードからバンドルを収集できない場合でもスクリプトが引き続き実行されます。
*** * Extra Args * ：このパラメータは 's_make _support_bundle' スクリプトに渡されますこのパラメータは、ネットアップサポートから指示された場合にのみ使用します。


.. * Delete All Support Bundles * ：管理ノードに保存されているすべてのサポートバンドルを削除します。
.. * ノードのリセット * ：管理ノードを新しいインストールイメージにリセットします。これにより、ネットワーク設定を除くすべての設定がデフォルトの状態に変更されます。次のオプションを指定します。
+
*** * Build * ：ノードをリセットするリモート Element ソフトウェアイメージの URL 。
*** * オプション * ：リセット操作を実行するための仕様。詳細が必要な場合は、ネットアップサポートにお問い合わせください。
+

IMPORTANT: この処理を実行すると、ネットワーク接続が一時的に失われます。



.. * ネットワークの再起動 * ：管理ノード上のすべてのネットワークサービスを再起動します。
+

IMPORTANT: この処理を実行すると、ネットワーク接続が一時的に失われます。







== 詳細はこちら

https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
