---
sidebar: sidebar 
permalink: docs/task_hcc_upgrade_compute_firmware_ansible.html 
summary: H シリーズのコンピューティングノードには Ansible のロールが用意されており、 BMC 、 BIOS 、 NIC などのハードウェアコンポーネントのファームウェアのアップグレードを自動化できます。 
keywords: netapp, hci, on premise, cluster, element, compute node, ansible upgrade, upgrade role 
---
= Ansible によるコンピューティングノードのファームウェアアップグレードの自動化
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Hybrid Cloud Control のワークフローを使用して、 NetApp HCI コンピューティングノードのシステムファームウェアを更新できます。これには、 BMC 、 BIOS 、 NIC などのコンポーネントのファームウェアも含まれます。大規模なコンピューティングクラスタを含む環境では、 Ansible を使用してクラスタ全体のローリングアップグレードを実行することでワークフローを自動化できます。


NOTE: コンピューティングノードのファームウェアアップグレードを自動化する Ansible のロールはネットアップによって提供されますが、自動化は補助コンポーネントとして機能し、追加のセットアップやソフトウェアコンポーネントの実行が必要となります。Ansible 自動化の変更はベストエフォートベースでのみサポートされます。


NOTE: アップグレード用の Ansible のロールは、 NetApp HCI H シリーズのコンピューティングノードでのみ機能します。サードパーティ製コンピューティングノードのアップグレードにはこのロールを使用できません。

.必要なもの
* * ファームウェアのアップグレードの準備と前提条件 * ：の手順に従って、 NetApp HCI のインストール環境でファームウェアのアップグレードの準備ができている必要があります link:task_hcc_upgrade_compute_node_firmware.html["ファームウェアのアップグレードを実行する"]。
* * Ansible コントロールノード * で自動化を実行する準備：物理サーバまたは仮想サーバで Ansible でファームウェア更新の自動化を実行します。


.このタスクについて
本番環境では、 NetApp HCI インストール環境のコンピューティングノードを、 1 つずつローリング方式で更新する必要があります。NetApp Hybrid Cloud Control の API は、健全性チェックの実行、コンピューティングノード上の ESXi のメンテナンス、ファームウェアアップグレードを適用するためのコンピューティングノードのリブートなど、コンピューティングノードのファームウェアアップグレードプロセス全体を 1 つのコンピューティングノードに対してオーケストレーションします。Ansible ロールは、コンピューティングノードのグループまたはクラスタ全体に対してファームウェアアップグレードをオーケストレーションするためのオプションを提供します。

.ファームウェアのアップグレードの自動化を始めましょう
作業を開始するには、に移動します https://github.com/NetApp-Automation/nar_compute_firmware_upgrade["GitHub 上の NetApp Ansible リポジトリ"^] および 'NAR_compute_nodes _firmware_upgrades ロールとドキュメントをダウンロードします
