---
sidebar: sidebar 
permalink: docs/task_trident_configure_networking.html 
summary: ユーザクラスタで Trident のサポートを有効にします。 
keywords: netapp, hci, netapp, networking, clusters, user, trident, rancher 
---
= ユーザクラスタで Trident のサポートを有効にします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp HCI 環境の管理ネットワークとストレージネットワークの間にルートがなく、 Trident のサポートが必要なユーザクラスタを導入する場合は、 Trident のインストール後にユーザクラスタネットワークをさらに設定する必要があります。各ユーザクラスタについて、管理ネットワークとストレージネットワークの間の通信を有効にする必要があります。これを行うには、ユーザクラスタ内の各ノードのネットワーク設定を変更します。

ユーザクラスタ内の各ノードのネットワーク設定を変更するには、次の一般的な手順を実行します。次の手順では、 NetApp HCI に Rancher をインストールしたデフォルトノードテンプレートを使用してユーザクラスタを作成したものとします。


NOTE: これらの変更をカスタムノードテンプレートの一部として追加すると、以降のユーザクラスタで使用できるようになります。

.手順
. 既存のデフォルトテンプレートを使用してユーザクラスタを導入する。
. ストレージネットワークをユーザクラスタに接続
+
.. 接続されている vCenter インスタンスの VMware vSphere Web Client を開きます。
.. ホストおよびクラスタインベントリツリーで、新しく導入したユーザクラスタ内のノードを選択します。
.. ノードの設定を編集します。
.. 設定ダイアログで、新しいネットワークアダプタを追加します。
.. [ 新しいネットワーク * ] ドロップダウン・リストで、ネットワークを参照し、 [* HCI _ 内部 _ ストレージ _ データ _ ネットワーク * ] を選択します。
.. [ ネットワークアダプタ ] セクションを展開し、新しいネットワークアダプタの MAC アドレスを記録します。
.. [OK] をクリックします。


. rancher で、ユーザクラスタ内の各ノードの SSH 秘密鍵ファイルをダウンロードします。
. ダウンロードした秘密鍵ファイルを使用して、ユーザクラスタ内のノードに SSH を使用して接続します。
+
[listing]
----
ssh -i <private key filename> <ip address>
----
. スーパーユーザーとして '/etc/netplan/50-cloud-init.yaml ファイルを編集して保存し ' 次の例のように ens224' セクションが含まれるようにします「 <MAC アドレス >` 」を、前に記録した MAC アドレスに置き換えます。
+
[listing]
----
network:
    ethernets:
        ens192:
            dhcp4: true
            match:
                macaddress: 00:50:56:91:1d:41
            set-name: ens192
        ens224:
            dhcp4: true
            match:
                macaddress: <MAC address>
            set-name: ens224
    version: 2
----
. 次のコマンドを使用して、ネットワークを再設定します。
+
[listing]
----
`netplan try`
----
. ユーザクラスタの残りのノードについて、手順 4~6 を繰り返します。
. ユーザクラスタ内の各ノードのネットワークを再設定したら、 Trident を利用するユーザクラスタにアプリケーションを導入できます。

