---
sidebar: sidebar 
permalink: docs/task_hci_hserieschassisrepl.html 
summary: シャーシにファンの障害または電源の問題がある場合は、できるだけ早く交換する必要があります。シャーシの交換手順は、 NetApp HCI 構成とクラスタの容量によって異なります。そのため、慎重な検討と計画が必要です。ネットアップサポートに連絡して指示を受け、交換用シャーシを注文する必要があります。 
keywords: netapp, hci, chassis replacement,2U chassis replacement, h-series 
---
= 2U H シリーズシャーシを交換
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
シャーシにファンの障害または電源の問題がある場合は、できるだけ早く交換する必要があります。シャーシの交換手順は、 NetApp HCI 構成とクラスタの容量によって異なります。そのため、慎重な検討と計画が必要です。ネットアップサポートに連絡して指示を受け、交換用シャーシを注文する必要があります。

シャーシを交換する前に、次の点を考慮してください。

* ラックに新しいシャーシ用のスペースは追加されていますか。
* 導入環境内のいずれかのシャーシに未使用のノードスロットがありますか？
* ラックにスペースが追加されている場合、障害が発生したシャーシから新しいシャーシに各ノードを一度に 1 つずつ移動できますか。この処理には時間がかかることがあります。
* 障害が発生したシャーシの一部であるノードを取り外しても、ストレージクラスタをオンラインのままにしておくことはできますか。
* 障害が発生したシャーシの一部であるコンピューティングノードを削除する際、仮想マシン（ VM ）と ESXi クラスタでワークロードを処理できますか？


次のいずれかのオプションを選択します。 the chassis when additional unused space is available in the rack
 the chassis when additional unused space is not available in the rack



== で追加の未使用スペースが使用可能になったら、シャーシを交換します ラック

ラックにスペースが追加されている場合は、新しいシャーシを設置し、ノードを一度に 1 つずつ新しいシャーシに移動できます。取り付けられているシャーシのいずれかに未使用のノードスロットがある場合、障害が発生したシャーシから未使用のスロットに一度に 1 つずつノードを移動して、障害が発生したシャーシを取り外すことができます。手順を開始する前に、ケーブル長が十分であり、スイッチポートが使用可能であることを確認してください。


NOTE: コンピューティングノードを移動する手順は、ストレージノードを移動する手順とは異なります。ノードを移動する前に、ノードが正しくシャットダウンされていることを確認する必要があります。障害が発生したシャーシからすべてのノードを移動したら、シャーシをラックから取り外してネットアップに返却する必要があります。



=== 新しいシャーシを設置します

新しいシャーシを設置して使用可能なラックスペースに設置し、ノードを移動できます。

.必要なもの
* 静電放電（ ESD ）リストバンドを装着するか、静電気防止処置を行っておきます。
* 交換用シャーシを用意しておきます。
* ステップを実施するために、リフトを 1 人または 2 人以上の作業者がいること。
* No.1 プラスドライバを用意しておきます。


.手順
. 静電気防止処置を施します。
. 交換用シャーシを開封します。障害が発生したシャーシをネットアップに返却するときは、パッケージを保管しておいてください。
. 出荷時にシャーシに付属していたレールを挿入します。
. 交換用シャーシをラックに挿入します。
+

TIP: シャーシを設置する際は、常に十分な人員またはリフトを使用してください。

. 前面取り付け用の蝶ネジでシャーシをラックに固定し、ネジをドライバで締めます。




=== コンピューティングノードを移動する

コンピューティングノードを新しいシャーシに移動したり、未使用のスロットがある既存のシャーシに移動したりする前に、仮想マシン（ VM ）を移行し、ノードを正しくシャットダウンして、ノードに挿入されているケーブルにラベルを付けたりする必要があります。


NOTE: ノードを移動するときは、静電気防止処置を施します。

.手順
. ノード背面のステッカーに記載されているノードのシリアル番号をメモします。
. VMware vSphere Web Client で、 *Hosts and Clusters* を選択し、ノード（ホスト）を選択してから * Monitor > Hardware Status > Sensor* を選択します。
. 「 * Sensors * 」セクションで、ノード背面のステッカーに記載されているシリアル番号を探します。
. 一致するシリアル番号が見つかったら、 VM を別の使用可能なホストに移行します。
+

NOTE: 移行手順については、 VMware のドキュメントを参照してください。

. ノードを右クリックし、 * 電源 > シャットダウン * を選択します。これで、ノードをシャーシから物理的に取り外す準備ができました。
. ノードの背面にあるノードとすべてのケーブルにラベルを付けます。
. 各ノードの右側にあるカムハンドルを下に引き、両方のカムハンドルを使用してノードをシャーシから引き出します。
. カチッという音がするまでノードを押し込んで、ノードを新しいシャーシに再度取り付けます。ノードを削除する前に付けておいたラベルは、ヘルプガイドに記載されています。ノードは、正しくインストールすると自動的に電源がオンになります。
+

CAUTION: ノードをインストールするときは、からサポートしていることを確認してください。ノードをシャーシにプッシュする際に力を入れすぎないようにしてください。

+

NOTE: 新しいシャーシに設置する場合は、ノードをシャーシの元のスロットに設置します。

. ノードの背面にある同じポートにケーブルを再接続します。ケーブルを外したときに使用していたラベルは、ガイドとして役立ちます。
+

CAUTION: ケーブルをポートに無理に押し込まないでください。ケーブル、ポート、またはその両方が破損する可能性があります。

. コンピューティングノード（ホスト）が VMware vSphere Web Client の ESXi クラスタに表示されることを確認します。
. 障害が発生したシャーシ内のすべてのコンピューティングノードで次の手順を実行します。




=== ストレージノードを移動

ストレージノードを新しいシャーシに移動する前に、ドライブを取り外し、ノードを正しくシャットダウンして、すべてのコンポーネントにラベルを付けておく必要があります。

.手順
. 次の手順で、削除するノードを特定します。
+
.. ノード背面のステッカーに記載されているノードのシリアル番号をメモします。
.. VMware vSphere Web Client で、 * NetApp Element Management* を選択し、 MVIP IP アドレスをコピーします。
.. Web ブラウザで MVIP IP アドレスを使用して、 NetApp Deployment Engine で設定したユーザ名とパスワードを使用して NetApp Element ソフトウェア UI にログインします。
.. [*Cluster] > [Nodes] を選択します。
.. 書き留めたシリアル番号と、記載されているシリアル番号（サービスタグ）を照合します。
.. ノードのノード ID をメモします。


. ノードを特定したら、次の API 呼び出しを使用して iSCSI セッションをノードから移動します。「 wget --no-check-certificate-q --user> -password=<user> -O-post-data' ｛ "method" ： "MovePrimaryiesAFrommNode " 、 "params" ： ｛ DEnodeID ｝ 」 https://<MVIP>/json-rpc/8.0`[]MVIP には MVIP IP アドレス、 NODEID にはノード ID 、 NetApp HCI のセットアップ時に NetApp Deployment Engine で設定したユーザ名にはユーザ名を、 NetApp HCI のセットアップ時に NetApp Deployment Engine で設定したパスワードには pass を指定します。
. クラスタ > ドライブ * を選択して、ノードに関連付けられているドライブを削除します。
+

NOTE: 取り外したドライブが使用可能として表示されるまで待ってから、ノードを削除します。

. ノードを削除するには、 * Cluster > Nodes > Actions > Remove * を選択します。
. 次の API 呼び出しを使用してノードをシャットダウンします。 `wget --no-check-certificate-q --user>--password=<pass> -O--post-data'{" method" ： "Shutdown" 、 "params" ： "option" 、 "nodes" ： [<NODEID> ｝ ] https://<MVIP>/json-rpc/8.0`[]MVIP には MVIP IP アドレス、 NODEID にはノード ID 、 NetApp HCI のセットアップ時に NetApp Deployment Engine で設定したユーザ名にはユーザ名を、 NetApp HCI のセットアップ時に NetApp Deployment Engine で設定したパスワードには pass を指定します。ノードがシャットダウンされると、シャーシからノードを物理的に取り外すことができます。
. 次の手順で、シャーシ内のノードからドライブを取り外します。
+
.. ベゼルを取り外します。
.. ドライブにラベルを付けます。
.. カムハンドルを開き、各ドライブを両手で慎重に引き出します。
.. ドライブを静電気防止処置を施した平らな場所に置きます。


. 次の手順でノードをシャーシから取り外します。
+
.. ノードとケーブルが接続されていることを示すラベルを付けます。
.. 各ノードの右側にあるカムハンドルを下に引き、両方のカムハンドルを使用してノードを引き出します。


. カチッという音がするまでノードを押し込んで、ノードをシャーシに再度取り付けます。ノードを削除する前に付けておいたラベルは、ヘルプガイドに記載されています。
+

CAUTION: ノードをインストールするときは、からサポートしていることを確認してください。ノードをシャーシにプッシュする際に力を入れすぎないようにしてください。

+

NOTE: 新しいシャーシに設置する場合は、ノードをシャーシの元のスロットに設置します。

. 各ドライブのカムハンドルをカチッと音がするまで押し下げて、ドライブをノードのそれぞれのスロットに取り付けます。
. ノードの背面にある同じポートにケーブルを再接続します。ケーブルを外したときに付けたラベルは、ガイドとして役立ちます。
+

CAUTION: ケーブルをポートに無理に押し込まないでください。ケーブル、ポート、またはその両方が破損する可能性があります。

. ノードの電源がオンになったら、クラスタにノードを追加します。
+

NOTE: ノードが追加されて「 * Nodes > Active * 」の下に表示されるまでに最大 2 分かかることがあります。

. ドライブを追加します。
. シャーシ内のすべてのストレージノードで次の手順を実行します。




== 追加の未使用スペースがない場合は、シャーシを交換します ラック内

ラックに追加のスペースがない場合や、設置されているシャーシに未使用のノードスロットがない場合は、交換手順を実行する前に、オンラインのまま維持できるノードを確認する必要があります。

シャーシの交換を行う前に、次の点を考慮する必要があります。

* 障害が発生したシャーシにストレージノードがない状態でも、ストレージクラスタをオンラインのままにしておくことはできますか。「いいえ」の場合は、 NetApp HCI 環境内のすべてのノード（コンピューティングとストレージの両方）をシャットダウンする必要があります。答えが「はい」の場合は、障害が発生したシャーシ内のストレージノードだけをシャットダウンできます。
* 障害が発生したシャーシにコンピューティングノードが搭載されていなくても、 VM と ESXi クラスタをオンラインのまま維持できますか？「いいえ」の場合は、障害が発生したシャーシのコンピューティングノードをシャットダウンできるように、適切な VM をシャットダウンまたは移行する必要があります。答えが「はい」の場合は、障害が発生したシャーシ内のコンピューティングノードだけをシャットダウンできます。




=== コンピューティングノードをシャットダウンします

コンピューティングノードを新しいシャーシに移動する前に、 VM を移行して正しくシャットダウンし、ノードに挿入したケーブルにラベルを付けます。

.手順
. ノード背面のステッカーに記載されているノードのシリアル番号をメモします。
. VMware vSphere Web Client で、 *Hosts and Clusters* を選択し、ノード（ホスト）を選択してから * Monitor > Hardware Status > Sensor* を選択します。
. 「 * Sensors * 」セクションで、ノード背面のステッカーに記載されているシリアル番号を探します。
. 一致するシリアル番号が見つかったら、 VM を別の使用可能なホストに移行します。
+

NOTE: 移行手順については、 VMware のドキュメントを参照してください。

. ノードを右クリックし、 * 電源 > シャットダウン * を選択します。これで、ノードをシャーシから物理的に取り外す準備ができました。




=== ストレージノードをシャットダウンします

手順を参照してください  a storage node,こちらをご覧ください。



=== ノードを削除します

ノードをシャーシから慎重に取り外し、すべてのコンポーネントにラベルを付ける必要があります。ノードを物理的に取り外す手順は、ストレージノードとコンピューティングノードで同じです。ストレージノードの場合は、ノードを削除する前にドライブを取り外してください。

.手順
. ストレージノードの場合は、次の手順でシャーシ内のノードからドライブを取り外します。
+
.. ベゼルを取り外します。
.. ドライブにラベルを付けます。
.. カムハンドルを開き、各ドライブを両手で慎重に引き出します。
.. ドライブを静電気防止処置を施した平らな場所に置きます。


. 次の手順でノードをシャーシから取り外します。
+
.. ノードとケーブルが接続されていることを示すラベルを付けます。
.. 各ノードの右側にあるカムハンドルを下に引き、両方のカムハンドルを使用してノードを引き出します。


. 削除するすべてのノードで次の手順を実行します。これで、障害が発生したシャーシを取り外す準備ができました。




=== シャーシを交換してください

ラックのスペースが足りない場合は、障害が発生したシャーシを取り外し、新しいシャーシと交換する必要があります。

.手順
. 静電気防止処置を施します。
. 交換用シャーシを開封し、平らな場所に保管します。障害ユニットをネットアップに返却するときは、梱包材を保管しておいてください。
. 障害が発生したシャーシをラックから取り外し、平らな場所に置きます。
+

NOTE: シャーシの移動中は、十分な人員またはリフトを使用してください。

. レールを取り外します。
. 交換用シャーシに付属している新しいレールを取り付けます。
. 交換用シャーシをラックに挿入します。
. 前面取り付け用の蝶ネジでシャーシをラックに固定し、ネジをドライバで締めます。
. 次の手順に従って、新しいシャーシにノードを設置します。
+
.. カチッという音がするまでノードを押し込んで、ノードをシャーシの元のスロットに再度取り付けます。ノードを削除する前に接続したラベル。
+

CAUTION: ノードをインストールするときは、からサポートしていることを確認してください。ノードをシャーシにプッシュする際に力を入れすぎないようにしてください。

.. ストレージノードの場合は、各ドライブのカムハンドルをカチッと音がするまで押し下げて、ドライブをノードのそれぞれのスロットに取り付けます。
.. ノードの背面にある同じポートにケーブルを再接続します。ケーブルを外したときに付けたラベルは、ガイドとして役立ちます。
+

CAUTION: ケーブルをポートに無理に押し込まないでください。ケーブル、ポート、またはその両方が破損する可能性があります。



. ノードが次のようにオンラインになっていることを確認します。
+
[cols="2*"]
|===
| オプション | 手順 


| すべてのノード（ストレージとコンピューティングの両方）を再インストールした場合 NetApp HCI 環境に導入します  a| 
.. VMware vSphere Web Client で、コンピューティングノード（ホスト）が ESXi クラスタに表示されていることを確認します。
.. Element Plug-in for vCenter Server で、ストレージノードが Active と表示されていることを確認します。




| 障害が発生したシャーシにノードだけを再設置した場合  a| 
.. VMware vSphere Web Client で、コンピューティングノード（ホスト）が ESXi クラスタに表示されていることを確認します。
.. vCenter Server 用 Element プラグインで、 * Cluster > Nodes > Pending * を選択します。
.. ノードを選択し、 * 追加 * を選択します。
+

NOTE: ノードが追加されて「 * Nodes > Active * 」の下に表示されるまでに最大 2 分かかることがあります。

.. [* Drives] を選択します。
.. 使用可能なリストからドライブを追加します。
.. 再インストールしたすべてのストレージノードで、次の手順を実行します。


|===
. ボリュームとデータストアが起動してアクセス可能であることを確認してください。




== 詳細については、こちらをご覧ください

* https://www.netapp.com/us/documentation/hci.aspx["NetApp HCI のリソースページ"^]
* http://docs.netapp.com/sfe-122/index.jsp["SolidFire と Element ソフトウェアドキュメントセンター"^]

