---
sidebar: sidebar 
permalink: docs/task_hci_credentials_vcenter_esxi.html 
summary: NetApp HCI 環境では、 NetApp Hybrid Cloud Control で管理されているコンピューティングノードの vCenter と ESXi ホストの両方のクレデンシャルを変更できます。 
keywords: netapp, hci, password, credential, vcenter, esxi, hybrid cloud control 
---
= vCenter および ESXi のクレデンシャルを更新します
:allow-uri-read: 


[role="lead"]
NetApp HCI 環境向けに NetApp Hybrid Cloud Control の全機能を維持するために、 vCenter および ESXi ホストでクレデンシャルを変更した場合は、管理ノードのアセットサービスでそれらのクレデンシャルも更新する必要があります。

NetApp Hybrid Cloud Control は、 VMware vSphere ESXi を実行している vCenter および個々のコンピューティングノードと通信し、ダッシュボードの情報を取得して、ファームウェア、ソフトウェア、ドライバのローリングアップグレードを支援します。NetApp Hybrid Cloud Control および管理ノード上の関連サービスでは、クレデンシャル（ユーザ名とパスワード）を使用して VMware vCenter および ESXi に対して認証されます。

これらのコンポーネント間の通信に障害が発生すると、 NetApp Hybrid Cloud Control と vCenter で認証の問題が発生したときにエラーメッセージが表示されます。NetApp HCI 環境の関連付けられた VMware vCenter インスタンスと通信できない場合、 NetApp Hybrid Cloud Control に赤色のエラーバナーが表示されます。VMware vCenter では、 NetApp Hybrid Cloud Control の使用時に古いクレデンシャルを使用して個々の ESXi ホストの ESXi アカウントロックアウトメッセージが表示されます。

NetApp HCI の管理ノードは、次の名前を使用してこれらのコンポーネントを参照します。

* 「コントローラアセット」は、 NetApp HCI 環境に関連付けられている vCenter インスタンスです。
* 「コンピューティングノードアセット」は、 NetApp HCI 環境の ESXi ホストです。


NetApp Deployment Engine を使用した NetApp HCI の初回インストール時には、 vCenter で指定した管理ユーザのクレデンシャルと ESXi サーバの「 root 」アカウントのパスワードが管理ノードに保存されます。



== 管理ノードの REST API を使用して vCenter のパスワードを更新します

手順に従ってコントローラアセットを更新します。を参照してください link:task_mnode_edit_vcenter_assets.html["既存のコントローラアセットを表示または編集する"]。



== 管理ノード REST を使用して ESXi のパスワードを更新します API

.手順
. 管理ノードの REST API ユーザインターフェイスの概要については、を参照してください link:task_mnode_work_overview_API.html["管理ノードの REST API ユーザインターフェイスの概要"]。
. 管理ノードの管理サービスの REST API UI にアクセスします。
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
+
management node IP> は、 NetApp HCI 用の管理ネットワーク上の管理ノードの IPv4 アドレスです。

. [* Authorize * （認証） ] または任意のロックアイコンをクリックして、次の手順を実行します。
+
.. NetApp SolidFire クラスタの管理ユーザ名とパスワードを入力します。
.. クライアント ID を「 m node-client 」として入力します。
.. セッションを開始するには、 * Authorize * をクリックします。
.. ウィンドウを閉じます。


. REST API UI で、 * Get 操作対象のデバイス / アセット / コンピュートノード * をクリックします。
+
管理ノードに格納されているコンピューティングノードアセットのレコードが取得されます。

+
UI からこの API に直接アクセスするには、次のリンクを使用します。

+
[listing]
----
https://<ManagementNodeIP>/mnode/#/assets/routes.v1.assets_api.get_compute_nodes
----
. [* 試してみてください * ] をクリックします。
. [* Execute] をクリックします。
. 応答の本文から、クレデンシャルの更新が必要なコンピューティングノードのアセットレコードを特定します。「 ip 」プロパティと「 host_name 」プロパティを使用して、正しい ESXi ホストレコードを検索できます。
+
[listing]
----
"config": { },
"credentialid": <credential_id>,
"hardware_tag": <tag>,
"host_name": <host_name>,
"id": <id>,
"ip": <ip>,
"parent": <parent>,
"type": ESXi Host
----
+

NOTE: 次の手順では、コンピューティングアセットレコードの「親」フィールドと「 id 」フィールドを使用して、更新するレコードを参照します。

. コンピューティングノードのアセットを設定します。
+
.. PUT /assets/｛ asset_id ｝ /compute-nodes / ｛ compute_id ｝ * をクリックします。
+
UI の API への直接リンクを次に示します。

+
[listing]
----
https://<ManagementNodeIP>/mnode/#/assets/routes.v1.assets_api.put_assets_compute_id
----
.. [* 試してみてください * ] をクリックします。
.. 「 parent 」情報を指定して「 asset_id 」を入力します。
.. "id" 情報を入力して、 "compute_id" を入力します。
.. ユーザインターフェイスの要求の本文を変更して、コンピューティングアセットレコードのパスワードとユーザ名のパラメータのみを更新します。
+
[listing]
----
{
"password": "<password>",
"username": "<username>"
}
----
.. [* Execute] をクリックします。
.. 応答が HTTP 200 であることを確認します。 HTTP 200 は、参照先のコンピューティングアセットレコードに新しいクレデンシャルが格納されたことを示します


. 新しいパスワードで更新する必要があるその他のコンピューティングノードアセットについて、前述の 2 つの手順を繰り返します。
. に移動します https://<mNode_ip>/inventory/1/[]。
+
.. [* Authorize * （認証） ] または任意のロックアイコンをクリックして、次の手順を実行します。
+
... NetApp SolidFire クラスタの管理ユーザ名とパスワードを入力します。
... クライアント ID を「 m node-client 」として入力します。
... セッションを開始するには、 * Authorize * をクリックします。
... ウィンドウを閉じます。


.. REST API UI で、 * GET / Installations * をクリックします。
.. [* 試してみてください * ] をクリックします。
.. [Refresh 概要（更新の設定） ] ドロップダウンリストから [* True] を選択します。
.. [* Execute] をクリックします。
.. 応答が HTTP 200 であることを確認します。


. vCenter のアカウントロックアウトメッセージが表示されなくなるまで約 15 分待ちます。


[discrete]
== 詳細については、こちらをご覧ください

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["NetApp HCI のリソースページ"^]

