---
sidebar: sidebar 
permalink: docs/task_hcc_update_management_services.html 
summary: NetApp HCI システムのアップグレードの一環として、管理サービスを更新する必要があります。 
keywords: netapp, hci, on premise, cluster, management services 
---
= 管理サービスを更新
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
管理ノード 11.3 以降をインストールしたら、管理サービスを最新のバンドルバージョンに更新できます。

Element 11.3 以降の管理ノードリリースでは、個々のサービスを提供する新しいモジュラアーキテクチャに基づいて管理ノードの設計が変更されました。これらのモジュラ型サービスは、 NetApp HCI システムの一元管理機能と拡張管理機能を提供します。管理サービスには、システム計測、ロギング、更新のサービス、 Element Plug-in for vCenter Server の QoSSIOC サービス、 NetApp Hybrid Cloud Control などがあります。

.このタスクについて
* Element ソフトウェアをアップグレードする前に、最新の管理サービスバンドルにアップグレードする必要があります。


[NOTE]
====
* 管理サービス2.22.7には、リモートプラグインを含むElement Plug-in for vCenter Server 5.0が含まれています。Elementプラグインを使用する場合は、ローカルプラグインのサポートを削除するVMwareの指示に従って、管理サービス2.22.7以降にアップグレードする必要があります。 https://kb.vmware.com/s/article/87880["詳細はこちら。"^]。
* 各サービスバンドルの主要なサービス、新機能、バグ修正、および対処方法について説明した最新の管理サービスリリースノートについては、を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["管理サービスのリリースノート"^]


====
.必要なもの
管理サービス2.20.69以降では、NetApp Hybrid Cloud ControlのUIまたはAPIを使用して管理サービスをアップグレードする前に、エンドユーザライセンス契約（EULA）に同意して保存する必要があります。

. Webブラウザで管理ノードのIPアドレスを開きます。
+
[listing]
----
https://<ManagementNodeIP>
----
. ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
. インターフェイスの右上にある [* Upgrade] を選択します。
. EULAがポップアップ表示されます。下にスクロールして、[現在および今後のすべての更新を許可する*]を選択し、[保存*]を選択します。


.オプションを更新します
管理サービスは、 NetApp Hybrid Cloud Control の UI または管理ノードの REST API を使用して更新できます。

* <<Hybrid Cloud Control を使用して管理サービスを更新します>> （推奨方法）
* <<管理ノード API を使用して管理サービスを更新する>>




== Hybrid Cloud Control を使用して管理サービスを更新します

NetApp Hybrid Cloud Control を使用してネットアップの管理サービスを更新できます。

管理サービスバンドルは、メジャーリリースに含まれていない機能の強化とインストールに対する修正を提供します。

.作業を開始する前に
* 管理ノード 11.3 以降が実行されていることを確認します。
* 管理サービスをバージョン 2.16 以降に更新する場合、管理ノード 11.3 から 11.8 を実行しているときは、管理サービスを更新する前に管理ノード VM の RAM を増やす必要があります。
+
.. 管理ノード VM の電源をオフにします。
.. 管理ノード VM の RAM を 12GB から 24GB RAM に変更します。
.. 管理ノード VM の電源をオンにします。


* クラスタで NetApp Element ソフトウェア 11.3 以降を実行している必要があります。
* 管理サービスをバージョン 2.1.326 以上にアップグレードしておきます。NetApp Hybrid Cloud Control のアップグレードは、それよりも前のサービスバンドルでは利用できません。



NOTE: 各サービスバンドルバージョンで使用可能なサービスのリストについては、を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["管理サービスリリースノート"^]。

.手順
. Webブラウザで管理ノードのIPアドレスを開きます。
+
[listing]
----
https://<ManagementNodeIP>
----
. ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
. インターフェイスの右上にある [* Upgrade] を選択します。
. アップグレードページで、 * 管理サービス * タブを選択します。
. ページの指示に従って、管理サービスのアップグレードパッケージをダウンロードし、コンピュータに保存します。
. 「 * 参照 * 」を選択して、保存したパッケージを検索し、アップロードします。
+
パッケージをアップロードすると、アップグレードが自動的に開始されます。

+
アップグレードの開始後は、このページにアップグレードのステータスが表示されます。アップグレードの実行中に NetApp Hybrid Cloud Control との接続が失われ、ログインし直さないとアップグレードの結果が表示されないことがあります。





== 管理ノード API を使用して管理サービスを更新する

管理サービスの更新は、 NetApp Hybrid Cloud Control から実行することを推奨します。ただし、 REST API を使用して、管理サービスのサービスバンドルの更新を管理ノードに手動でアップロード、展開、および導入することができます。管理ノード用の REST API UI から各コマンドを実行できます。

.作業を開始する前に
* NetApp Element ソフトウェア管理ノード 11.3 以降を導入しておきます。
* 管理サービスをバージョン 2.16 以降に更新する場合、管理ノード 11.3 から 11.8 を実行しているときは、管理サービスを更新する前に管理ノード VM の RAM を増やす必要があります。
+
.. 管理ノード VM の電源をオフにします。
.. 管理ノード VM の RAM を 12GB から 24GB RAM に変更します。
.. 管理ノード VM の電源をオンにします。


* クラスタで NetApp Element ソフトウェア 11.3 以降を実行している必要があります。
* 管理サービスをバージョン 2.1.326 以上にアップグレードしておきます。NetApp Hybrid Cloud Control のアップグレードは、それよりも前のサービスバンドルでは利用できません。
+

NOTE: 各サービスバンドルバージョンで使用可能なサービスのリストについては、を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["管理サービスリリースノート"^]。



.手順
. 管理ノードで REST API UI を開きます https://<ManagementNodeIP>/mnode`
. 「 * Authorize * 」（認証）を選択して、次の手順を実行
+
.. クラスタのユーザ名とパスワードを入力します。
.. 値がまだ入力されていない場合は、クライアント ID を「 m node-client 」として入力します。
.. セッションを開始するには、 * Authorize * を選択します。
.. ウィンドウを閉じます。


. 管理ノードにサービスバンドルをアップロードして展開するには 'put/services/upload' コマンドを使用します
. 管理ノードに管理サービスを配備します :PUT /services/deploy
. 更新のステータスを監視します。「 get/services/update/status 」
+
更新が成功すると、次の例のような結果が返されます。

+
[listing]
----
{
"current_version": "2.10.29",
"details": "Updated to version 2.17.52",
"status": "success"
}
----




== 詳細については、こちらをご覧ください

https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]
