---
sidebar: sidebar 
permalink: docs/task_hcc_manage_accounts.html 
summary: ユーザアカウントを作成してボリュームに関連付ける方法について説明します。 
keywords: netapp, hci, on premise, cluster, element, account, user, volume, hybrid cloud control, hcc 
---
= ネットアップハイブリッドクラウドを使用してユーザアカウントを作成、管理します 制御
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Element ベースのストレージシステムでは、「管理者」または「読み取り専用」のユーザに付与する権限に応じて、権限のあるクラスタユーザを作成して NetApp Hybrid Cloud Control へのログインアクセスを有効にすることができます。クラスタユーザに加えてボリュームアカウントもあり、クライアントはこのアカウントを使用してストレージノード上のボリュームに接続できます。 

次のタイプのアカウントを管理します。

* <<権限のあるクラスタアカウントを管理します>>
* <<ボリュームアカウントを管理する>>




== LDAP を有効にします

任意のユーザアカウントで LDAP を使用するには、最初に LDAP を有効にする必要があります。

.手順
. NetApp HCI または Element ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
. ダッシュボードで、右上の [ オプション ] アイコンをクリックし、 [ * ユーザー管理 * ] を選択します。
. [ ユーザー ] ページで、 [*LDAP の構成 *] をクリックします。
. LDAP 設定を定義します。
. 検索とバインドまたは直接バインドの認証タイプを選択します。
. 変更を保存する前に、ページ上部の「 * LDAP ログインのテスト * 」をクリックし、既存のユーザーのユーザー名とパスワードを入力して、「 * テスト * 」をクリックします。
. [ 保存（ Save ） ] をクリックします。




== 権限のあるクラスタアカウントを管理します

link:concept_cg_hci_accounts.html#authoritative-user-accounts["権限のあるユーザアカウント"] NetApp Hybrid Cloud Control の右上のメニューから User Management オプションを選択して管理します。このタイプのアカウントでは、ノードおよびクラスタの NetApp Hybrid Cloud Control インスタンスに関連付けられているストレージアセットに対して認証を行うことができます。このアカウントを使用すると、すべてのクラスタのボリューム、アカウント、アクセスグループなどを管理できます。



=== 権限のあるクラスタアカウントを作成してください

NetApp Hybrid Cloud Control を使用してアカウントを作成できます。

このアカウントを使用して、 Hybrid Cloud Control 、クラスタのノード UI 、および NetApp Element ソフトウェアのストレージクラスタにログインできます。

.手順
. NetApp HCI または Element ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
. ダッシュボードで、右上の [ オプション ] アイコンをクリックし、 [ * ユーザー管理 * ] を選択します。
. [Create User] を選択します。
. クラスタまたは LDAP の認証タイプを選択します。
. 次のいずれかを実行します。
+
** LDAP を選択した場合は、 DN を入力します。
+

TIP: LDAP を使用するには、最初に LDAP または LDAPS を有効にする必要があります。を参照してください <<LDAP を有効にします>>。

** Auth Type として Cluster を選択した場合は、新しいアカウントの名前とパスワードを入力します。


. 管理者権限または読み取り専用権限のいずれかを選択します。
+

TIP: NetApp Element ソフトウェアからアクセス許可を表示するには、 [ 従来のアクセス許可を表示する *] をクリックします。これらの権限のサブセットを選択すると、そのアカウントには読み取り専用権限が割り当てられます。すべてのレガシー権限を選択した場合、そのアカウントには管理者権限が割り当てられます。

+

TIP: グループのすべての子が権限を継承するようにするには、 LDAP サーバで DN 組織管理者グループを作成します。そのグループのすべての子アカウントは、これらの権限を継承します。

. 「ネットアップのエンドユーザライセンス契約を読んで同意します」というボックスをオンにします。
. [ ユーザーの作成 ] をクリックします。




=== 権限のあるクラスタアカウントを編集してください

NetApp Hybrid Cloud Control を使用して、ユーザアカウントの権限またはパスワードを変更できます。

.手順
. NetApp HCI または Element ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
. ダッシュボードで右上のアイコンをクリックし、 * ユーザー管理 * を選択します。
. 必要に応じて、 * Cluster * 、 * LDAP * 、または * IDP * を選択して、ユーザアカウントのリストをフィルタリングします。
+
ストレージクラスタで LDAP を使用してユーザを設定している場合、それらのアカウントのユーザタイプは「 LDAP 」と表示されます。 IdP を使用してストレージクラスタにユーザを設定した場合、設定したアカウントのユーザタイプは「 IDP 」と表示されます。

. テーブルの * アクション * 列で、アカウントのメニューを展開し、 * 編集 * を選択します。
. 必要に応じて変更します。
. [ 保存（ Save ） ] を選択します。
. NetApp Hybrid Cloud Control からログアウトします。
. link:task_mnode_manage_storage_cluster_assets.html#edit-the-stored-credentials-for-a-storage-cluster-asset["クレデンシャルを更新します"] NetApp Hybrid Cloud Control API を使用して、権限のあるクラスタアセットに対してアクセスします。
+

NOTE: NetApp Hybrid Cloud Control の UI でインベントリの更新に最大 2 分かかる場合があります。インベントリを手動で更新するには、 REST API UI インベントリサービス https://<ManagementNodeIP>/inventory/1/` にアクセスし、クラスタに対して「 get/installationses/{ id} 」を実行します。

. NetApp Hybrid Cloud Control にログインします。




=== 権限のあるユーザアカウントを削除します

不要になったアカウントを削除できます。LDAP ユーザアカウントを削除できます。

権限のあるクラスタのプライマリ管理者ユーザアカウントを削除することはできません。

.手順
. NetApp HCI または Element ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
. ダッシュボードで右上のアイコンをクリックし、 * ユーザー管理 * を選択します。
. ユーザーテーブルの * アクション * 列で、アカウントのメニューを展開し、 * 削除 * を選択します。
. [ はい ] を選択して、削除を確認します。




== ボリュームアカウントを管理する

link:concept_cg_hci_accounts.html#volume-accounts["ボリュームアカウント"] NetApp Hybrid Cloud Control Volumes の表で管理します。これらのアカウントは、アカウントを作成したストレージクラスタにのみ固有です。これらのタイプのアカウントでは、ネットワーク上のボリュームにアクセス許可を設定できますが、設定したボリューム以外には影響しません。

ボリュームアカウントには、そのボリュームにアクセスするために必要な CHAP 認証が含まれています。



=== ボリュームアカウントを作成します

このボリュームに固有のアカウントを作成します。

.手順
. NetApp HCI または Element ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
. ダッシュボードで、 * ストレージ * > * ボリューム * を選択します。
. 「 * アカウント * 」タブを選択します。
. 「 * アカウントの作成 * 」ボタンを選択します。
. 新しいアカウントの名前を入力します。
. CHAP Settings （ CHAP 設定）セクションで、次の情報を入力します。
+
** CHAP ノードセッション認証用のイニシエータシークレット
** Target Secret ： CHAP ノードセッション認証
+

NOTE: いずれかのパスワードを自動生成する場合は、クレデンシャルのフィールドを空白のままにします。



. 「 * アカウントの作成 * 」を選択します。




=== ボリュームアカウントを編集します

CHAP 情報を変更し、アカウントがアクティブであるかロックされているかを変更できます。


IMPORTANT: 管理ノードに関連付けられているアカウントを削除またはロックすると、管理ノードにアクセスできなくなります。

.手順
. NetApp HCI または Element ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
. ダッシュボードで、 * ストレージ * > * ボリューム * を選択します。
. 「 * アカウント * 」タブを選択します。
. テーブルの * アクション * 列で、アカウントのメニューを展開し、 * 編集 * を選択します。
. 必要に応じて変更します。
. 「 * はい * 」を選択して変更を確定します。




=== ボリュームアカウントを削除します

不要になったアカウントを削除します。

ボリュームアカウントを削除する前に、そのアカウントに関連付けられているボリュームを削除およびパージします。


IMPORTANT: 管理ノードに関連付けられているアカウントを削除またはロックすると、管理ノードにアクセスできなくなります。


NOTE: 管理サービスに関連付けられた永続ボリュームは、インストールまたはアップグレード時に新しいアカウントに割り当てられます。永続ボリュームを使用している場合は、ボリュームや関連付けられているアカウントを変更または削除しないでください。これらのアカウントを削除すると、管理ノードが使用できなくなる可能性があります。

.手順
. NetApp HCI または Element ストレージクラスタ管理者のクレデンシャルを指定して NetApp Hybrid Cloud Control にログインします。
. ダッシュボードで、 * ストレージ * > * ボリューム * を選択します。
. 「 * アカウント * 」タブを選択します。
. テーブルの * アクション * 列で、アカウントのメニューを展開し、 * 削除 * を選択します。
. [ はい ] を選択して、削除を確認します。




== 詳細については、こちらをご覧ください

* link:concept_cg_hci_accounts.html["アカウントの詳細を確認します"]
* http://docs.netapp.com/sfe-122/topic/com.netapp.doc.sfe-ug/GUID-E93D3BAF-5A60-414D-86AF-0C1F86D43F26.html["ユーザアカウントを操作する"^]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server 向け NetApp Element プラグイン"^]

