---
sidebar: sidebar 
permalink: docs/task_nde_access_manual_ip.html 
summary: NetApp HCI ノードに IP アドレスを手動で割り当てて、 NetApp Deployment Engine にアクセスする方法を説明します。 
keywords: netapp, hci, netapp deployment engine, deployment, engine, deploy, access 
---
= NetApp Deployment Engine にアクセスするには、 IP アドレスを手動で割り当ててください
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: hci, release notes, vcp, element, management services, firmware


[role="lead"]
すべての NetApp HCI ノードの Bond1G インターフェイスと Bond10G インターフェイスに静的 IPv4 アドレスを手動で割り当て、 NetApp Deployment Engine にアクセスして NetApp HCI を導入することができます。ネットワークに特別な要件がないかぎり、この方法は使用しないでください。

.必要なもの
* 自分またはネットワーク管理者が、『セットアップガイド』ドキュメントのタスクを完了している。
* NetApp HCI ノードに物理的にアクセスできるようにしておきます。
* すべての NetApp HCI ノードの電源をオンにしておきます。
* NetApp HCI ネットワークで DHCP が有効になっておらず、 NetApp HCI ノードが DHCP サーバから IP アドレスを取得していません。注： NetApp Deployment Engine を使用してシステムを導入する前に手動で割り当てる IP アドレスはすべて一時的な IP アドレスであり、再利用することはできません。IP アドレスを手動で割り当てる場合は、最終的な導入時に割り当て可能な、未使用かつ永続的な IP アドレスのセットをもう 1 つ確保しておく必要があります。


.このタスクについて
この構成では、導入時にコンピューティングノードとストレージノードが静的 IPv4 アドレスを使用して他のノードを検出して通信を確立します。この構成は推奨されません。

.手順
. いずれかの NetApp HCI ストレージノードの背面に KVM を接続します（このノードが制御用ストレージノードになります）。
. ユーザインターフェイスで Bond1G および Bond10G の IP アドレス、サブネットマスク、ゲートウェイアドレスを設定します。必要に応じて、各ネットワークの VLAN ID を設定することもできます。
. 残りのストレージノードとコンピューティングノードについて手順 2 を繰り返します。
. NetApp HCI 管理ネットワークにアクセスできるコンピュータで Web ブラウザを開きます。
. 制御用ストレージノードに割り当てた Bond1G の IP アドレスにアクセスします。例：
+
[listing]
----
http://<Bond1G IP address>
----
+
NetApp Deployment Engine のユーザインターフェイスが表示されます。



[discrete]
== 詳細については、こちらをご覧ください

* link:firmware_driver_versions.html["NetApp HCI でサポートされるファームウェアとESXiドライバのバージョン、NetApp HCI ストレージノードでサポートされるファームウェアのバージョンとファームウェアのバージョン"]

